# Shell variables
# Generated by 'wal'
wallpaper='/home/mxnkr/Pictures/cropped-1920-1080-826965.png'

# Special
background='#0A0101'
foreground='#f6e6e0'
cursor='#f6e6e0'

# Colors
color0='#0A0101'
color1='#D53E2D'
color2='#FAA152'
color3='#FAA966'
color4='#2D65AB'
color5='#EBB096'
color6='#FECF9D'
color7='#f6e6e0'
color8='#aca19c'
color9='#D53E2D'
color10='#FAA152'
color11='#FAA966'
color12='#2D65AB'
color13='#EBB096'
color14='#FECF9D'
color15='#f6e6e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
